// countries.ts
export const COUNTRIES = [
  { value: "Afghanistan",            label: "Afghanistan",            dialCode: "93",   flag: "🇦🇫" },
  { value: "Albania",                label: "Albania",                dialCode: "355",  flag: "🇦🇱" },
  { value: "Algeria",                label: "Algeria",                dialCode: "213",  flag: "🇩🇿" },
  { value: "Andorra",                label: "Andorra",                dialCode: "376",  flag: "🇦🇩" },
  { value: "Angola",                 label: "Angola",                 dialCode: "244",  flag: "🇦🇴" },
  { value: "Argentina",              label: "Argentina",              dialCode: "54",   flag: "🇦🇷" },
  { value: "Armenia",                label: "Armenia",                dialCode: "374",  flag: "🇦🇲" },
  { value: "Australia",              label: "Australia",              dialCode: "61",   flag: "🇦🇺" },
  { value: "Austria",                label: "Austria",                dialCode: "43",   flag: "🇦🇹" },
  { value: "Azerbaijan",             label: "Azerbaijan",             dialCode: "994",  flag: "🇦🇿" },
  { value: "Bahrain",                label: "Bahrain",                dialCode: "973",  flag: "🇧🇭" },
  { value: "Bangladesh",             label: "Bangladesh",             dialCode: "880",  flag: "🇧🇩" },
  { value: "Belarus",                label: "Belarus",                dialCode: "375",  flag: "🇧🇾" },
  { value: "Belgium",                label: "Belgium",                dialCode: "32",   flag: "🇧🇪" },
  { value: "Bolivia",                label: "Bolivia",                dialCode: "591",  flag: "🇧🇴" },
  { value: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina", dialCode: "387",  flag: "🇧🇦" },
  { value: "Brazil",                 label: "Brazil",                 dialCode: "55",   flag: "🇧🇷" },
  { value: "Bulgaria",               label: "Bulgaria",               dialCode: "359",  flag: "🇧🇬" },
  { value: "Cambodia",               label: "Cambodia",               dialCode: "855",  flag: "🇰🇭" },
  { value: "Cameroon",               label: "Cameroon",               dialCode: "237",  flag: "🇨🇲" },
  { value: "Canada",                 label: "Canada",                 dialCode: "1",    flag: "🇨🇦" },
  { value: "Chile",                  label: "Chile",                  dialCode: "56",   flag: "🇨🇱" },
  { value: "China",                  label: "China",                  dialCode: "86",   flag: "🇨🇳" },
  { value: "Colombia",               label: "Colombia",               dialCode: "57",   flag: "🇨🇴" },
  { value: "Croatia",                label: "Croatia",                dialCode: "385",  flag: "🇭🇷" },
  { value: "Cuba",                   label: "Cuba",                   dialCode: "53",   flag: "🇨🇺" },
  { value: "Cyprus",                 label: "Cyprus",                 dialCode: "357",  flag: "🇨🇾" },
  { value: "Czech Republic",         label: "Czech Republic",         dialCode: "420",  flag: "🇨🇿" },
  { value: "Denmark",                label: "Denmark",                dialCode: "45",   flag: "🇩🇰" },
  { value: "Ecuador",                label: "Ecuador",                dialCode: "593",  flag: "🇪🇨" },
  { value: "Egypt",                  label: "Egypt",                  dialCode: "20",   flag: "🇪🇬" },
  { value: "Estonia",                label: "Estonia",                dialCode: "372",  flag: "🇪🇪" },
  { value: "Ethiopia",               label: "Ethiopia",               dialCode: "251",  flag: "🇪🇹" },
  { value: "Finland",                label: "Finland",                dialCode: "358",  flag: "🇫🇮" },
  { value: "France",                 label: "France",                 dialCode: "33",   flag: "🇫🇷" },
  { value: "Georgia",                label: "Georgia",                dialCode: "995",  flag: "🇬🇪" },
  { value: "Germany",                label: "Germany",                dialCode: "49",   flag: "🇩🇪" },
  { value: "Ghana",                  label: "Ghana",                  dialCode: "233",  flag: "🇬🇭" },
  { value: "Greece",                 label: "Greece",                 dialCode: "30",   flag: "🇬🇷" },
  { value: "Guatemala",              label: "Guatemala",              dialCode: "502",  flag: "🇬🇹" },
  { value: "Honduras",               label: "Honduras",               dialCode: "504",  flag: "🇭🇳" },
  { value: "Hungary",                label: "Hungary",                dialCode: "36",   flag: "🇭🇺" },
  { value: "India",                  label: "India",                  dialCode: "91",   flag: "🇮🇳" },
  { value: "Indonesia",              label: "Indonesia",              dialCode: "62",   flag: "🇮🇩" },
  { value: "Iran",                   label: "Iran",                   dialCode: "98",   flag: "🇮🇷" },
  { value: "Iraq",                   label: "Iraq",                   dialCode: "964",  flag: "🇮🇶" },
  { value: "Ireland",                label: "Ireland",                dialCode: "353",  flag: "🇮🇪" },
  { value: "Israel",                 label: "Israel",                 dialCode: "972",  flag: "🇮🇱" },
  { value: "Italy",                  label: "Italy",                  dialCode: "39",   flag: "🇮🇹" },
  { value: "Jamaica",                label: "Jamaica",                dialCode: "1876", flag: "🇯🇲" },
  { value: "Japan",                  label: "Japan",                  dialCode: "81",   flag: "🇯🇵" },
  { value: "Jordan",                 label: "Jordan",                 dialCode: "962",  flag: "🇯🇴" },
  { value: "Kazakhstan",             label: "Kazakhstan",             dialCode: "7",    flag: "🇰🇿" },
  { value: "Kenya",                  label: "Kenya",                  dialCode: "254",  flag: "🇰🇪" },
  { value: "Kosovo",                 label: "Kosovo",                 dialCode: "383",  flag: "🇽🇰" },
  { value: "Kuwait",                 label: "Kuwait",                 dialCode: "965",  flag: "🇰🇼" },
  { value: "Latvia",                 label: "Latvia",                 dialCode: "371",  flag: "🇱🇻" },
  { value: "Lebanon",                label: "Lebanon",                dialCode: "961",  flag: "🇱🇧" },
  { value: "Libya",                  label: "Libya",                  dialCode: "218",  flag: "🇱🇾" },
  { value: "Lithuania",              label: "Lithuania",              dialCode: "370",  flag: "🇱🇹" },
  { value: "Luxembourg",             label: "Luxembourg",             dialCode: "352",  flag: "🇱🇺" },
  { value: "Malaysia",               label: "Malaysia",               dialCode: "60",   flag: "🇲🇾" },
  { value: "Malta",                  label: "Malta",                  dialCode: "356",  flag: "🇲🇹" },
  { value: "Mexico",                 label: "Mexico",                 dialCode: "52",   flag: "🇲🇽" },
  { value: "Moldova",                label: "Moldova",                dialCode: "373",  flag: "🇲🇩" },
  { value: "Monaco",                 label: "Monaco",                 dialCode: "377",  flag: "🇲🇨" },
  { value: "Montenegro",             label: "Montenegro",             dialCode: "382",  flag: "🇲🇪" },
  { value: "Morocco",                label: "Morocco",                dialCode: "212",  flag: "🇲🇦" },
  { value: "Netherlands",            label: "Netherlands",            dialCode: "31",   flag: "🇳🇱" },
  { value: "New Zealand",            label: "New Zealand",            dialCode: "64",   flag: "🇳🇿" },
  { value: "Nigeria",                label: "Nigeria",                dialCode: "234",  flag: "🇳🇬" },
  { value: "North Macedonia",        label: "North Macedonia",        dialCode: "389",  flag: "🇲🇰" },
  { value: "Norway",                 label: "Norway",                 dialCode: "47",   flag: "🇳🇴" },
  { value: "Pakistan",               label: "Pakistan",               dialCode: "92",   flag: "🇵🇰" },
  { value: "Palestine",              label: "Palestine",              dialCode: "970",  flag: "🇵🇸" },
  { value: "Panama",                 label: "Panama",                 dialCode: "507",  flag: "🇵🇦" },
  { value: "Paraguay",               label: "Paraguay",               dialCode: "595",  flag: "🇵🇾" },
  { value: "Peru",                   label: "Peru",                   dialCode: "51",   flag: "🇵🇪" },
  { value: "Philippines",            label: "Philippines",            dialCode: "63",   flag: "🇵🇭" },
  { value: "Poland",                 label: "Poland",                 dialCode: "48",   flag: "🇵🇱" },
  { value: "Portugal",               label: "Portugal",               dialCode: "351",  flag: "🇵🇹" },
  { value: "Qatar",                  label: "Qatar",                  dialCode: "974",  flag: "🇶🇦" },
  { value: "Romania",                label: "Romania",                dialCode: "40",   flag: "🇷🇴" },
  { value: "Russia",                 label: "Russia",                 dialCode: "7",    flag: "🇷🇺" },
  { value: "Saudi Arabia",           label: "Saudi Arabia",           dialCode: "966",  flag: "🇸🇦" },
  { value: "Senegal",                label: "Senegal",                dialCode: "221",  flag: "🇸🇳" },
  { value: "Serbia",                 label: "Serbia",                 dialCode: "381",  flag: "🇷🇸" },
  { value: "Singapore",              label: "Singapore",              dialCode: "65",   flag: "🇸🇬" },
  { value: "Slovakia",               label: "Slovakia",               dialCode: "421",  flag: "🇸🇰" },
  { value: "Slovenia",               label: "Slovenia",               dialCode: "386",  flag: "🇸🇮" },
  { value: "Somalia",                label: "Somalia",                dialCode: "252",  flag: "🇸🇴" },
  { value: "South Africa",           label: "South Africa",           dialCode: "27",   flag: "🇿🇦" },
  { value: "South Korea",            label: "South Korea",            dialCode: "82",   flag: "🇰🇷" },
  { value: "Spain",                  label: "Spain",                  dialCode: "34",   flag: "🇪🇸" },
  { value: "Sri Lanka",              label: "Sri Lanka",              dialCode: "94",   flag: "🇱🇰" },
  { value: "Sudan",                  label: "Sudan",                  dialCode: "249",  flag: "🇸🇩" },
  { value: "Sweden",                 label: "Sweden",                 dialCode: "46",   flag: "🇸🇪" },
  { value: "Switzerland",            label: "Switzerland",            dialCode: "41",   flag: "🇨🇭" },
  { value: "Syria",                  label: "Syria",                  dialCode: "963",  flag: "🇸🇾" },
  { value: "Taiwan",                 label: "Taiwan",                 dialCode: "886",  flag: "🇹🇼" },
  { value: "Thailand",               label: "Thailand",               dialCode: "66",   flag: "🇹🇭" },
  { value: "Tunisia",                label: "Tunisia",                dialCode: "216",  flag: "🇹🇳" },
  { value: "Turkey",                 label: "Turkey",                 dialCode: "90",   flag: "🇹🇷" },
  { value: "Ukraine",                label: "Ukraine",                dialCode: "380",  flag: "🇺🇦" },
  { value: "United Arab Emirates",   label: "United Arab Emirates",   dialCode: "971",  flag: "🇦🇪" },
  { value: "United Kingdom",         label: "United Kingdom",         dialCode: "44",   flag: "🇬🇧" },
  { value: "United States",          label: "United States",          dialCode: "1",    flag: "🇺🇸" },
  { value: "Uruguay",                label: "Uruguay",                dialCode: "598",  flag: "🇺🇾" },
  { value: "Uzbekistan",             label: "Uzbekistan",             dialCode: "998",  flag: "🇺🇿" },
  { value: "Venezuela",              label: "Venezuela",              dialCode: "58",   flag: "🇻🇪" },
  { value: "Vietnam",                label: "Vietnam",                dialCode: "84",   flag: "🇻🇳" },
  { value: "Yemen",                  label: "Yemen",                  dialCode: "967",  flag: "🇾🇪" },
  { value: "Zimbabwe",               label: "Zimbabwe",               dialCode: "263",  flag: "🇿🇼" },
];

export type Country = typeof COUNTRIES[number];